# Generated by Django 5.2.5 on 2025-09-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_create_video_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Actor1Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='Actor2Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
