# Generated by Django 5.2.5 on 2025-09-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_add_actor1'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='DirectorName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='MovieGenre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ReleaseYear',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
