# Generated by Django 5.2.5 on 2025-09-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_add_directorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
